$(document).ready(function(){
    $('.openSitebararea').click(function(){
        $('#navSidebar').toggleClass('opensidebar');
        $('#main').toggleClass('mainboxarea');
    });
    $('a.notification').click(function(){
        $(this).toggleClass('active');
    });
});
